-- Create help_requests table
create table if not exists help_requests (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  location text,
  timestamp text not null
);

-- Create helpers table
create table if not exists helpers (
  id bigint generated by default as identity primary key,
  name text not null,
  skill text not null,
  category text not null,
  availability text not null,
  contact_method text not null,
  contact_info text not null,
  timestamp text not null
);

-- Enable RLS (Row Level Security)
alter table help_requests enable row level security;
alter table helpers enable row level security;

-- Create policies to allow read and write access for all users
create policy "Allow read access to help_requests" on help_requests
  for select using (true);

create policy "Allow insert access to help_requests" on help_requests
  for insert with check (true);

create policy "Allow read access to helpers" on helpers
  for select using (true);

create policy "Allow insert access to helpers" on helpers
  for insert with check (true);